#!/bin/bash
set -e
sudo add-apt-repository universe -n -y
sudo apt update
sudo apt install curl -y

echo "Ulauncher app launcher"
sudo add-apt-repository ppa:agornostal/ulauncher -n -y

echo "Alacritty"
sudo add-apt-repository ppa:aslatter/ppa -y

echo "Better diff tool used with git"
sudo add-apt-repository ppa:aos1/diff-so-fancy -n -y

echo "Spotify"
curl -sS https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg
echo "deb http://repository.spotify.com stable non-free" | sudo tee /etc/apt/sources.list.d/spotify.list

