#!/bin/bash
set -e

# Aliases
git config --global alias.co checkout
git config --global alias.br branch
git config --global alias.ci commit
git config --global alias.st status

# Use diff-so-fancy
git config --global core.pager "diff-so-fancy | less --tabs=4 -RFX"
