#!/bin/bash
set -e

echo "# Configure your git config#":
echo "git config user.name 'Conrado Garcia Berrotaran'"
echo "git config user.email 'example@mail.com'"
echo "Remember to deactivate CAPS-LOCK in gnome-tweaks: set it to Caps-lock is disabled"
echo "Install nvidia drivers (from website, not from Additional drivers)"
